[package]
name = "rusty-slider"
version = "0.5.0"
authors = ["Olle Wreede <olle@wreede.se>"]
edition = "2018"
license = "MIT"
description = "A small tool to display markdown files as a slideshow."
repository = "https://github.com/ollej/rusty-slider"
homepage = "https://ollej.github.io/rusty-slider/"
readme = "README.md"
categories = ["command-line-utilities"]
keywords = ["markdown", "slide", "presentation", "graphics", "wasm"]

[dependencies]
colorsys = "0.6.3"
image = "0.23.14"
macroquad = "0.3.0"
markdown = { git = "https://github.com/johannhof/markdown.rs" }
nanoserde = "0.1.25"
structopt = "0.3.21"
syntect = { version = "4.5", default-features = false, features = ["default-fancy"]}
getrandom = { version = "0.2", features = ["js"] }
quad-url = "0.1.0"

# Doesn't work with android build
[profile.dev.package.'*']
opt-level = 3

[package.metadata.scripts]
build-web = "bin/build-web"
build-linux = "bin/build-linux"
build-win = "bin/build-win"
serve-web = "bin/serve-web"
build-apk = "bin/build-apk"
